<html>
	<head>
		<style>
			body {
				background-color:#ffccff;
			}
		</style>
	</head>
	<body>
		<h1>SAML SERVICE PROVIDER (SP)</h1>
		<h2>Welcome to our service!</h2>
		<h3>USER MENU</h3>
		<ul>
			<li><a href='/login'>log in using your Federated user account</a></li>
			<li><a href='/logout'>log out</a></li>
		</ul>
		<h3>FEDERATION COMMUNICATION</h3>
		<ul>
			<li><a href='/metadata'>SAML SP metadata</a></li>
			<li><a href='/consume'>endpoint where authentication assertions are received</a></li>
			<li><a href='https://www.samltool.com/validate_response.php' target='_new'>Authentication Assertion Validator</a></li>
		</ul>
		<img id='service_provider_image' src='images/nyan_cat.png' style='max-width:800px;' />
	</body>
</html>
