<html>
	<head>
		<style>
			body {
				background-color:#ccffcc;
			}
		</style>
	</head>
	<body>
		<h1>GOOGLE IDENTITY PROVIDER (IdP)</h1>
		<h2>Using Google to log into a site</h2>
		<ul>
			<li><a target='_new' href='https://plex.tv'>log in via google</a></li>
		</ul>
		<h2>Join the Google Federation</h2>
		<ul>
			<li><a target='_new' href='https://developers.google.com/'>Google Developers Login</a>
			<li><a target='_new' href='https://console.developers.google.com/'>Google API Console</a>
		</ul>
		<img id='google_image' src='images/Googlelogo.png' style='max-width:800px;' />
	</body>
</html>
