<html>
	<head>
		<style>
			body {
				background-color:#ffffcc;
			}
		</style>
	</head>
	<body>
		<h1>LEARNING TOOLS INTEROPERABILITY SERVICE PROVIDER (SP)</h1>
		<h2>A Learning Management System (LMS) logs into this service using LTI</h2>
		<ul>
			<li><a href='/xml' target='_new'>Get Config XML</a></li>
			<li><a href='https://canvas.instructure.com/' target='_new'>Go to Canvas LMS</a></li>
		</ul>
		<h3>Helpful LTI Links</h3>
		<ul>
			<li><a target='_new' href='http://www.spvsoftwareproducts.com/'>LMS Tools by Stephen P. Vickers</a></li>
			<li><a target='_new' href='http://lti.tools/test/tc.php'>LTI Emulation Tools</a></li>
			<li><a target='_new' href='https://www.imsglobal.org/activity/learning-tools-interoperability'>IMS Global LTI Overview</a></li>
			<li><a target='_new' href='https://www.imsglobal.org/specs/ltiv1p1/implementation-guide'>IMS Global LTI Implementation Guide</a></li>
			<li><a target='_new' href='https://www.imsglobal.org/specs/lti/xml'>IMS Global LTI XML Schemas</a></li>
			<li><a target='_new' href='https://www.edu-apps.org/build_xml.html'>LTI XML Config Builder at edu-apps.org</a></li>
		</ul>
		<img id='lti_image' src='images/ims_global.jpg' style='max-width:800px;' />
	</body>
</html>
