<html>
	<head>
		<style>
			body {
				background-color:#00ffcc;
			}
		</style>
	</head>
	<body>
		<h1>LEARNING TOOLS INTEROPERABILITY SERVICE PROVIDER (SP)</h1>
		<h2>A Learning Management System (LMS) logs into this service using LTI</h2>
		<ul>
			<li><a href='https://canvas.instructure.com/' target='_new'>Go to Canvas LMS</a></li>
		</ul>
		<img id='lti_image' src='images/lti.gif' style='max-width:800px;' />
	</body>
</html>
