<html>
	<head>
		<style>
			body {
				background-color:#00ffcc;
			}
		</style>
	</head>
	<body>
		<h1>SAML IDENTITY PROVIDER (IdP)</h1>
		<h2>Hello, <?php echo $user_email; ?></h2>
		<h3>DASHBOARD</h3>
		<div>
			SSO into one of our federated service providers:
		</div>
		<ul>
			<li><a href='/sso'>SAML SSO TEST</a></li>
		</ul>
		<img id='federation_image' src='images/rebel_alliance.jpg' style='max-width:400px;'/>
	</body>
</html>
