<html>
	<head>
		<style>
			body {
				background-color:#00ffcc;
			}
		</style>
	</head>
	<body>
		<h1>SAML IDENTITY PROVIDER (IdP)</h1>
		<h2>Have you joined the federation?</h2>
		<h3>USER MENU</h3>
		<ul>
			<li><a href='/login'>log in</a></li>
			<li><a href='/dashboard'>SSO into a federated service provider</a></li>
			<li><a href='/logout'>log out</a></li>
		</ul>
		<h3>FEDERATED SERVICE PROVIDERS</h3>
		<ul>
			<li><a href='/metadata'>get SAML metadata</a></li>
			<li><a href='/getauth'>request authorization assertion</a></li>
		</ul>
		<img id='federation_image' src='images/articles_of_confederation.gif' style='max-width:800px;' />
	</body>
</html>
