<html>
	<head>
		<style>
			body {
				background-color:#00ffcc;
			}
		</style>
	</head>
	<body>
		<h1>SAML IDENTITY PROVIDER (IdP)</h1>
		<h2>Have you joined the federation?</h2>
		<h3>USER LOGIN</h3>
		<form name='login' action='/login' method='post'>
			<p>Please enter your email address</p>
			<div>
				<input type='text' name='email' value='' />
			</div>
			<div>
				<input type='submit' value='submit' />
			</div>
		</form>
		<img id='federation_image' src='images/united_federation_of_planets.png' style='max-width:800px;'/>
	</body>
</html>
