<html>
	<head>
		<style>
			body {
				background-color:#ccffff;
			}
		</style>
	</head>
	<body>
		<h1>FACEBOOK IDENTITY PROVIDER (IdP)</h1>
		<h2>Using facebook to log into a site</h2>
		<ul>
			<li><a target='_new' href='https://plex.tv'>log in via facebook</a></li>
		</ul>
		<h2>Join the Facebook Confederation</h2>
		<ul>
			<li><a target='_new' href='https://developers.facebook.com/'>Facebook Developers Login</a>
		</ul>
		<img id='facebook_image' src='images/facebook.svg' style='max-width:800px;' />
	</body>
</html>
